package com.ruici.ai.modules.knowledgebase.service;

import com.ruici.ai.modules.knowledgebase.model.KnowledgeBaseEntity;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("RAG 聊天会话标题测试")
class RagChatSessionServiceTest {

    @Nested
    @DisplayName("默认标题生成")
    class DefaultTitleGeneration {

        @Test
        @DisplayName("单知识库新会话使用通用标题而不是知识库名称")
        void shouldUseGenericTitleForSingleKnowledgeBase() {
            String title = RagChatSessionService.generateTitle(List.of(knowledgeBase(1L, "Java 面试题库")));

            assertThat(title).isEqualTo("新对话");
        }

        @Test
        @DisplayName("多知识库新会话显示知识库数量")
        void shouldShowKnowledgeBaseCountForMultipleKnowledgeBases() {
            String title = RagChatSessionService.generateTitle(List.of(
                knowledgeBase(1L, "Java 面试题库"),
                knowledgeBase(2L, "Spring 实战手册")
            ));

            assertThat(title).isEqualTo("新对话（2 个知识库）");
        }
    }

    @Nested
    @DisplayName("首问标题生成")
    class QuestionTitleGeneration {

        @Test
        @DisplayName("首问标题会压缩多余空白")
        void shouldNormalizeWhitespaceInQuestionTitle() {
            String title = RagChatSessionService.buildQuestionTitle("  请   帮我总结   这份简历的亮点  ");

            assertThat(title).isEqualTo("请 帮我总结 这份简历的亮点");
        }

        @Test
        @DisplayName("过长首问标题会被截断")
        void shouldTruncateLongQuestionTitle() {
            String title = RagChatSessionService.buildQuestionTitle("请帮我总结这份简历在Java后端岗位上的核心优势和明显短板有哪些");

            assertThat(title)
                .endsWith("...")
                .startsWith("请帮我总结这份简历在Java后端岗位上的")
                .hasSize(23);
        }
    }

    @Nested
    @DisplayName("自动改名判定")
    class AutoUpdateDecision {

        @Test
        @DisplayName("旧逻辑生成的知识库名标题也会被视为自动标题")
        void shouldTreatLegacyKnowledgeBaseNameAsAutoGenerated() {
            Set<KnowledgeBaseEntity> knowledgeBases = new LinkedHashSet<>(List.of(
                knowledgeBase(1L, "Java 面试题库")
            ));

            boolean result = RagChatSessionService.shouldAutoUpdateTitle("Java 面试题库", knowledgeBases);

            assertThat(result).isTrue();
        }

        @Test
        @DisplayName("用户自定义标题不会被自动覆盖")
        void shouldNotTreatCustomTitleAsAutoGenerated() {
            Set<KnowledgeBaseEntity> knowledgeBases = new LinkedHashSet<>(List.of(
                knowledgeBase(1L, "Java 面试题库")
            ));

            boolean result = RagChatSessionService.shouldAutoUpdateTitle("春招一面准备", knowledgeBases);

            assertThat(result).isFalse();
        }
    }

    private static KnowledgeBaseEntity knowledgeBase(Long id, String name) {
        KnowledgeBaseEntity entity = new KnowledgeBaseEntity();
        entity.setId(id);
        entity.setName(name);
        return entity;
    }
}
